[book]
authors = ["Dango"]
language = "en"
src = "src"
title = "Buckyball Technical Documentation"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[_TOC_]]"
max-level = 5

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
